project_name: gwebtail
dist: .bin
builds:
  - id: gwebtail
    binary: "gwebtail"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags: "-s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"

archives:
  - id: gwebtail
    name_template: >-
      {{.ProjectName}}_
      {{- .Tag}}_
      {{- if eq .Os "darwin"}}macos
      {{- else if eq .Os "windows"}}win
      {{- else}}{{.Os}}{{end}}_
      {{- if eq .Arch "amd64"}}x86_64
      {{- else if eq .Arch "386"}}i386
      {{- else}}{{.Arch}}{{end}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
    # rlcp: true

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "docker.io/bsv9/gwebtail:{{ .Version }}-amd64"
      - "docker.io/bsv9/gwebtail:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "docker.io/bsv9/gwebtail:{{ .Version }}-arm64"
      - "docker.io/bsv9/gwebtail:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "docker.io/bsv9/gwebtail:{{ .Tag }}"
    image_templates:
      - "docker.io/bsv9/gwebtail:{{ .Tag }}-amd64"
      - "docker.io/bsv9/gwebtail:{{ .Tag }}-arm64"
